Announce 1.1.4
* Convert all error messages to use a Java resource bundle.
* Maven artifact is now OSGi ready (thanks to Matt Bishop
  [https://github.com/mbishop]).
* Full hyperschema syntax validation support (as a result, added dependency on
  uri-template [https://github.com/fge/uri-template]).

Francis Galiegue (67):
      Announce 1.1.3
      Start a test file for hyperschema syntax validation
      Add dictionary for hyper schema syntax checking
      Start to implement draft v4 hyper schema syntax checking
      Add syntax check tests for fragmentResolution
      Add hyper schema tests for readOnly
      Add draft v4 hyper-schema in resources
      Revert "Add hyper schema tests for readOnly"
      Start and implement hyper schema's "media" keyword
      Start and add dedicated "media" hyperschema syntax validation class
      Add one more (positive) "media" test
      Continue hyperschema "media" keyword syntax tests
      Complete "media" syntax checking tests
      Start to add hyperschema's "links" syntax checking
      Continue "links" syntax checking
      Continue "links" syntax checking
      More "links" syntax checking
      More "links" syntax checking
      More "links" syntax checking
      Continue LDO syntax checking
      Start refactor of LDO syntax checking
      Continue refactor of LDO syntax checking
      Refactor links syntax checking again
      Continue "links" syntax checking
      Continue "links" syntax checking
      Complete individual member tests for LDOs
      SchemaVersion: add draft v4 hyper schema
      pom.xml: update uri-template dependency
      Add a simple schema expander class
      Add problematic schema to illustrate performance problem
      SchemaExpander: make a copy of nodes we get
      Fixes to SchemaExpander
      Update README
      Remove unneeded fully qualified names
      Add jsr305 as a provided dependency, modify code accordingly
      Update dependencies for uri-template, jackson-coreutils
      ProcessingError: add a single string constructor
      DictionaryBuilder: convert error messages to use a resource bundle
      JsonReferenceErrors: remove an unused enum entry
      JsonRef: start to convert error messages to use a resource bundle
      Get rid of RefSanityChecks
      Get rid of JsonReferenceErrors, now unused
      Convert loading configuration error messages to a resource bundle
      Add a resource bundle for processing error messages
      ProcessorMap: use the newly created resource bundle
      ProcessingErrors: remove now unused keys
      CachingProcessor: use the resource bundle
      ProcessingResult: use the resource bundle
      ProcessorChain: use the resource bundle
      New class MessageBundle
      ProcessorSelector: convert to use MessageBundle
      More conversions to MessageBundle
      Get rid of ProcessingErrors
      MessageBundle: add a .message() method
      Add a ref processing message bundle
      RefResolver: use a message bundle
      SchemaLoader: use a resource bundle
      URIManager: use a resource bundle
      Create a message bundle for schema walker
      SchemaWalkerMessages: convert to use a message bundle
      Create bundle for syntax messages
      ResolvingSchemaWalker: use the syntax message bundle
      SyntaxProcessor: use the syntax message bundle
      LinksSyntaxChecker: rename one message method
      LinksSyntaxChecker: change LDOmsg prototype
      Remove SyntaxMessages
      syntax.properties: convert all keys to camelCase instead of UPPER_CASE

mbishop (1):
      Modify pom.xml for OSGi-capable deployments